config/routes.rb
Gallery::Application.routes.draw do
  get 'paypal_notifications/pdt'

  devise_for :users

  root :to => 'categories#index'

  resources :categories, :only => [:index, :show]

  resource :cart, :controller => 'Cart', :only => [:show, :update] do
    member do
      post :add
      delete :remove
    end
  end

  resources :orders, :only => [:index, :show] do
    member do
      get :download
    end
  end

  namespace :admin do
    root :to => 'categories#index'
    resources :categories do
      collection do
        post :sort
        delete :delete_photo
      end
    end

    resources :orders, :only => :index
  end

  match '/:a/:b/:c/:d/:id' => "categories#show"
  match '/:a/:b/:c/:id'    => "categories#show"
  match '/:a/:b/:id'       => "categories#show"
  match '/:a/:id'          => "categories#show"
  match '/:id'             => "categories#show"
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :inverse_of => :cart
  has_many :photos, :through => :line_items
  belongs_to :promo

  before_create :generate_uuid

  attr_accessible :promo_code

  attr_accessor :promo_code

  validate :validate_promo_use, if: lambda { promo_code.present? }

  def add(photo_id, line_item_attrs = {})
    return if line_items.find_by_photo_id(photo_id)

    line_items.build(line_item_attrs).tap do |li|
      li.photo_id = photo_id
    end.save!
  end

  def remove(photo_id)
    line_items.find_by_photo_id(photo_id).delete
  end

  def total
    [total_before_promo - promo_discount, 0].max
  end

  def total_before_promo
    line_items.to_a.sum(&:unit_price)
  end

  def promo_discount
    return 0.0 if !promo

    total_before_percent_discount = total_before_promo - promo.fixed_discount

    percent_discount = total_before_percent_discount *
      (promo.percentage_discount * 0.01)

    promo.fixed_discount + percent_discount
  end

  private

  def validate_promo_use
    promo = Promo.find_by_code(promo_code)
    if promo_code && promo.try(:valid?, :use)
      self.promo_id = promo.id
    else
      errors.add(:promo_code, 'is invalid')
    end
  end

  def generate_uuid
    # http://stackoverflow.com/questions/1117584/guids-in-ruby
    self.uuid ||= (0..16).to_a.map{|a| rand(16).to_s(16)}.join
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_filter :load_cart

  def add
    @cart.add(params[:photo_id], :size => params[:size])

    respond_to do |format|
      format.html { redirect_to :back }
      format.js   { render :layout => false }
    end
  end

  def remove
    @cart.remove(params[:photo_id])

    respond_to do |format|
      format.html { redirect_to @cart }
    end
  end

  def show
  end

  def update
    if @cart.update_attributes(params[:cart])
      respond_to do |format|
        format.html { redirect_to cart_path }
      end
    else
      respond_to do |format|
        format.html { render action: 'show' }
      end
    end
  end

  private

  def load_cart
    @cart = Cart.find_or_create_by_session_id(request.session_options[:id])
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/_cart.html.haml
%li#cart
  - if @cart
    = link_to cart_path do
      %span.cart-title Your Cart
      %i.icon-shopping-cart.icon-large
      .cart-count= @cart.line_items.count

app/views/cart/add.js.erb
"<%= escape_javascript(render 'cart/cart') %>"

app/views/cart/show.html.haml
- if @cart.photos.empty?
  .well
    There are no photos in your cart.
    = link_to 'Browse Photos', root_path

- else

  .well
    .row
      .span7
        .well
          %h3 Photos
          %ul.thumbnails
            - @cart.line_items.each do |li|
              %li.span2
                .thumbnail
                  = link_to li.photo.image.url(:large), :class => 'thumb' do
                    = image_tag li.photo.image.url(:thumb)

                  = link_to remove_cart_url(:photo_id => li.photo.id),
                    method: :delete, rel: 'tooltip', class: "delete pull-right",
                    title: 'Remove from cart' do
                    %i.icon-remove-sign.icon-large

                  .caption
                    #{li.size.capitalize} (#{number_to_currency(li.unit_price)})

          :javascript
            $('html').on('contextmenu', 'img', function() { return false; });

      %fieldset.span4.download
        %legend Download

        %ul
          %li After purchasing, items will be available as a digital download.
          %li
            I do prints also, but for now you'll need to #{contact_me}
            to order those.
          %li
            Note: you do not need a PayPal account to check out. Look for
            the 'pay as a guest' link if you do not wish to create one.

        .well
          All images purchased and downloaded from this site are subject to a
          = link_to "Personal Use License", '#personal-use-licence',
            data: {toggle: 'modal'}
          \. For a
          = link_to "Commercial Use Licence", '#commercial-use-licence',
            data: {toggle: 'modal'}
          and pricing, please #{contact_me}.

        - if @cart.errors[:promo_code].any?
          %p.alert.alert-error Promo code #{@cart.errors[:promo_code].join(', ')}

        = link_to 'Have a promo code?', '#promo-code', data: {toggle: 'modal'}

        %table.table
          - if @cart.promo_id.present?
            %tr
              %th Promo #{@cart.promo.code}
              %td #{number_to_currency(@cart.promo_discount)} off
          %tr
            %th Order Total
            %td.order-total= number_to_currency(@cart.total)

        = link_to root_path, class: 'browse' do
          %i.icon-signin
          Continue Browsing

        = link_to PaypalPayment.new(@cart, with: :size).checkout_url,
          id: 'paypal-checkout' do

          <img src="https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif"
          align="right" style="margin-right:7px;">

    .clearfix

#promo-code.hide.modal
  = form_for @cart, url: cart_path do |cart_f|
    .modal-body
      = cart_f.label :promo_code, "Promotional Code"
      = cart_f.text_field :promo_code, class: 'pull-left'

    .modal-footer
      = link_to 'Cancel', '#', data: {dismiss: 'modal'}, class: 'btn'
      = submit_tag 'Apply', class: 'btn btn-primary'

#personal-use-licence.hide.modal
  .modal-header
    %h3.strong Personal Use License

  .modal-body
    %p
      This license is for personal use only. Personal use means non-commercial
      use of the Media for display on personal websites and computers, or
      making image prints or video copies for personal use. The Media may not
      be used in any way whatsoever in which you charge money, collect fees, or
      receive any form of remuneration. The Media may not be used in
      advertising. The Media may not be resold, relicensed, or sub-licensed.

    %ul
      %li
        Title and ownership, and all right now and in the future, of and for
        the Media remain exclusively with the content provider.
      %li
        There are no warranties, express or implied. The media are provided 'as
        is'.

  .modal-footer
    = link_to 'I understand', '#', data: {dismiss: 'modal'}, class: 'btn'

#commercial-use-licence.hide.modal
  .modal-header
    %h3.strong Commercial Use Licence

  .modal-body
    %ul
      %li
        Photographer (“content provider”) grants you a perpetual, non-exclusive,
        non-transferable, worldwide license to use the accompanying image(s), for
        permitted commercial purpose, defined as:

        %ul
          %li Advertising, promotion, brochures, packing
          %li As part of a commercial website for promotional purposes (maximum 800x600 pixels)
          %li Prints, posters, flyers, for promotional uses only (not for resale)
          %li Prints, posters, or other commercial display of media
          %li Magazines, books, newspapers, other printed publications, 
          %li Video, broadcast, theatrical

    %h5.strong What you may not do:

    %p
      Buyer may not resell, relicense, redistribute, without express written
      permission from content provider. Use as a derivative work, and reselling
      or redistributing such as derivative work is prohibited. Media may not be
      used in a pornographic, obscene, illegal, immoral, libelous, or
      defamatory manner. Media may not be incorporated into trademarks, logos,
      or service marks. Media may not be made available for download.

    %p
      Content provider retains all rights, license, copyright, title and
      ownership of the Media.

    %p
      There is no warranty, express or implied, with the purchase of this
      digital image file. Content provider will not be made liable for any
      claims, or incidental, consequential or other damages arising out of this
      license or buyers use of media.

  .modal-footer
    = link_to 'I understand', '#', data: {dismiss: 'modal'}, class: 'btn'