config/routes.rb
Gallery::Application.routes.draw do
  get 'paypal_notifications/pdt'

  devise_for :users

  root :to => 'categories#index'

  resources :categories, :only => [:index, :show]

  resource :cart, :controller => 'Cart', :only => [:show, :update] do
    member do
      post :add
      delete :remove
    end
  end

  resources :orders, :only => [:index, :show] do
    member do
      get :download
    end
  end

  namespace :admin do
    root :to => 'categories#index'
    resources :categories do
      collection do
        post :sort
        delete :delete_photo
      end
    end

    resources :orders, :only => :index
  end

  match '/:a/:b/:c/:d/:id' => "categories#show"
  match '/:a/:b/:c/:id'    => "categories#show"
  match '/:a/:b/:id'       => "categories#show"
  match '/:a/:id'          => "categories#show"
  match '/:id'             => "categories#show"
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :photos_attributes, :parent_id

  has_ancestry

  extend FriendlyId
  friendly_id :name, use: [:slugged, :scoped], scope: :ancestry

  belongs_to :user, :inverse_of => :categories
  has_many :photos, :inverse_of => :category,
    :dependent => :destroy

  accepts_nested_attributes_for :photos

  validates :name, :presence => true
  validates_associated :photos

  scope :having_photos,
    joins('LEFT JOIN photos ON photos.category_id = categories.id').
    where('photos.id IS NOT NULL').
    uniq
  scope :without_photos,
    joins('LEFT JOIN photos ON photos.category_id = categories.id').
    where('photos.id IS NULL').
    uniq
  scope :after_date, lambda {|date| where('categories.created_at > ?', date)}

  # This is a bit non-rails-standard due to jquery file upload.
  # This receives a hash whose only key is 'images',
  # and whose value is an array of uploaded images.
  def photos_attributes=(photos_attributes)
    self.photos += photos_attributes['images'].map do |image|
      photo = Photo.new(image: image)
      photo.category_id = self.id
      photo
    end
  end

  def has_photos?
    photos.any?
  end
end

app/controllers/admin/categories_controller.rb
require 'ostruct'
class Admin::CategoriesController < AdminController
  load_and_authorize_resource
  before_filter :redirect_to_new_if_no_categories, :only => :index
  before_filter :load_categories_unless_present
  after_filter :expire_category_cache, :only => [:update, :delete_photo]

  def index
    redirect_to [:admin, @categories.last]
  end

  def show
    respond_to do |format|
      format.html # just render
      format.json { render json: @category.photos.map(&:as_jq_upload).to_json}
    end
  end

  def create
    if @category.save
      redirect_to [:admin, @category]
    else
      render :action => :new
    end
  end

  def update
    if @category.update_attributes(params[:category])
      respond_to do |format|
        format.html { redirect_to [:admin, @category] }
        format.json { render json: @category.photos.map(&:as_jq_upload).to_json}
      end
    else
      respond_to do |format|
        format.html { render :action => :show }
        format.json { render :json => [{error: @category.errors.full_messages}]}
      end
    end
  end

  def sort
    @category.update_attributes(params[:category])
    respond_to do |format|
      format.js
    end
  end

  # too lazy to make a controller just for this
  def delete_photo
    photo = Photo.find(params[:photo_id])

    if can?(:delete, photo)
      photo.destroy
    end

    respond_to do |format|
      format.html { redirect_to [:admin, photo.category] }
      format.json { render json: photo.as_jq_upload.to_json }
    end
  end

  private

  def load_categories_unless_present
    unless request.xhr?
      @categories ||= Category.accessible_by(current_ability)
    end
  end

  def redirect_to_new_if_no_categories
    redirect_to :action => :new if @categories.empty?
  end

  def expire_category_cache
    expire_fragment(@category)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :load_recent_categories
  load_and_authorize_resource
  skip_load_and_authorize_resource :only => :index

  before_filter :load_cart

  def show
  end

  # will be cleared on app restart due to transient nature of
  # in-memory cache; good enough for now
  caches_action :index, layout: false

  def index
    @carousel_photos = CarouselPhoto.scoped
    if @carousel_photos.any?
      render
    elsif @recent_categories.first
      redirect_to @recent_categories.first
    else
      render text: 'what do you want from me!?!'
    end
  end

  private

  def load_recent_categories
    @recent_categories = Category.having_photos.accessible_by(current_ability).
      after_date(Date.today.beginning_of_year).order('id DESC').limit(5)
  end

  def load_cart
    @cart = Cart.find_by_session_id(request.session_options[:id])
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
  def nested_categories(categories)
    categories.map do |category, sub_categories|
      render(category) + content_tag(:ul, nested_categories(sub_categories),
                                     class: 'nav nav-tabs nav-stacked nested_categories')
    end.join.html_safe
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_recent_albums.html.haml
.clearfix
  %ul.filter-nav
    - @recent_categories.each do |category|
      %li{:class => active_category(category, :current => @category)}
        = link_to category.name, category

app/views/categories/_recent_categories.html.haml
.clearfix
  .row
    .span10
      %ul.filter-nav
        - @recent_categories.each do |category|
          %li{:class => active_category(category, :current => @category)}
            = link_to category.name, category

    .span2{style: 'text-align: right'}
      %ul.filter-nav
        - Category.where(name: [Date.today.year.to_s, 1.year.ago.year.to_s]).order('name DESC').all.each do |category|
          %li{:class => active_category(category, current: @category,
            include_ancestry: true)}
            = link_to category.name, category

app/views/categories/index.html.haml
= render 'recent_categories'

.row
  .span5
    .lead
      %p.first
        Welcome to khouck photography, where you can find photos of many local
        cycling events!
      %p
        You can now purchase and download images from the site. I can
        do prints as well, but for now you will need to #{contact_me} for those.
      %p
        You can follow me on
        = link_to 'Facebook', 'http://www.facebook.com/khouckphoto'
        to stay updated as I add more images and
        events. Please feel free to contact me with any questions or feedback you
        may have about my site.

      %p Thank you!

      %p Katie

  .span7.pull-right
    #index-carousel.carousel.slide
      .carousel-inner
        - @carousel_photos.each do |carousel_photo|
          .item
            = link_to category_path(carousel_photo.photo.category_id) do
              = image_tag carousel_photo.photo.image(:large)

      = link_to '&lsaquo;'.html_safe, '#index-carousel',
        :class => "carousel-control left", 'data-slide' => "prev"
      = link_to '&rsaquo;'.html_safe, '#index-carousel',
        :class => "carousel-control right", 'data-slide' => "next"

:javascript
  $(function() {
    $('.carousel .item:first').addClass('active');
    $('.carousel').carousel({ });
  })

app/views/categories/show.html.haml
= render 'recent_categories'

.cart-flash.hide
  .alert.alert-success
    Updated cart

- cache(@category) do

  %ul#thumbnails.thumbnails
    - if @category.has_children?
      - @category.children.having_photos.each do |child|
        %li.span4
          = link_to child do
            .category-image
              = image_tag child.photos.first.image.url(:medium)
              .category-name-shadow
              .category-name
                = child.name

    - else
      - @category.photos.order(:image_file_name).each do |photo|
        %li.span2.thumbnail[photo]
          = link_to "##{dom_id(photo)}-large", :class => 'photo-link inline' do
            = image_tag photo.image.url(:medium)

          .hidden
            .fullsize{:id => "#{dom_id(photo)}-large"}
              = image_tag photo.image.url(:large),
                oncontextmenu: "$('##{dom_id(photo)}-cart-btn').click(); return false"

              .cart.btn-group
                %a.btn.btn-primary.dropdown-toggle{'data-toggle' => 'dropdown',
                  id: "#{dom_id(photo)}-cart-btn"}
                  %i.icon-shopping-cart

                %ul.dropdown-menu.purchase-options
                  %li
                    %h4 Downloads
                  %li
                    = link_to add_cart_url(photo_id: photo.id, size: 'small'),
                      :class => 'image-small', :method => :post, :remote => true do
                      Small
                      .pull-right
                        $5.00
                      %br
                      (~1Mpix)
                  %li
                    = link_to add_cart_url(photo_id: photo.id, size: 'medium'),
                      :class => 'image-medium', :method => :post, :remote => true do
                      Medium
                      .pull-right
                        $10.00
                      %br
                      (~4Mpix)
                  %li
                    = link_to add_cart_url(photo_id: photo.id, size: 'large'),
                      :class => 'image-large', :method => :post, :remote => true do
                      Large
                      .pull-right
                        $15.00
                      %br
                      (original)

          .caption
            %i.zoom.icon-zoom-in